FROM node:8 AS node-builder

COPY . /app/
RUN cd /app/ \
    && npm install \
    && npm run build

FROM nginx:1.14-alpine
COPY --from=node-builder /app/ /app/
RUN set -ex \
    && apk add --no-cache bash tzdata \
    && mv /app/dist/* /usr/share/nginx/html/ \
    && mv /app/nginx.conf /etc/nginx/nginx.conf \
    && mv /app/run.sh /usr/share/ \
    && chmod +x /usr/share/run.sh  \
    && rm -rf /app
    
EXPOSE 80
CMD /usr/share/run.sh && nginx -g 'daemon off;'
