export default [
  {
    o: 'Global',
    name: 'Global Brief',
    comp: 'ChartBrief',
    title: 'Global Brief',
    type: 'global',
    width: 3,
  },
  {
    o: 'Database',
    name: 'Database Avg Response',
    comp: 'ChartAvgResponse',
    title: 'Database Avg Response',
    type: 'databaseInfo',
    width: 3,
  },
  {
    o: 'Database',
    name: 'Database Avg Throughput',
    comp: 'ChartAvgThroughput',
    title: 'Database Avg Throughput',
    type: 'databaseInfo',
    width: 3,
  },
  {
    o: 'Database',
    name: 'Database Avg SLA',
    comp: 'ChartAvgSLA',
    title: 'Database Avg SLA',
    type: 'databaseInfo',
    width: 3,
  },
  {
    o: 'Global',
    name: 'Global Percent Response(line)',
    comp: 'ChartResponseLine',
    title: 'Global Percent Response',
    type: 'global',
    width: 3,
  },
  {
    o: 'Database',
    name: 'Database Percent Response',
    comp: 'ChartResponse',
    title: 'Database Percent Response',
    type: 'databaseInfo',
    width: 3,
  },
  {
    o: 'Database',
    name: 'Database Top Slow SQL',
    comp: 'ChartTraceDB',
    title: 'Database Top Slow SQL',
    type: 'databaseInfo.getTopNRecords',
    width: 6,
  },
];
