export default [
  {
    o: 'Global',
    name: 'Global Brief',
    comp: 'ChartBrief',
    title: 'Global Brief',
    type: 'global',
    width: 3,
  },
  {
    o: 'ServiceEndpoint',
    name: 'Endpoint Avg Response',
    comp: 'ChartAvgResponse',
    title: 'Endpoint Avg Response',
    type: 'endpointInfo',
    width: 3,
  },
  {
    o: 'ServiceEndpoint',
    name: 'Endpoint Avg Throughput',
    comp: 'ChartAvgThroughput',
    title: 'Endpoint Avg Throughput',
    type: 'endpointInfo',
    width: 3,
  },
  {
    o: 'ServiceEndpoint',
    name: 'Endpoint Avg SLA',
    comp: 'ChartAvgSLA',
    title: 'Endpoint Avg SLA',
    type: 'endpointInfo',
    width: 3,
  },
  {
    o: 'Global',
    name: 'Global Percent Response(line)',
    comp: 'ChartResponseLine',
    title: 'Global Percent Response',
    type: 'global',
    width: 3,
  },
  {
    o: 'ServiceEndpoint',
    name: 'Endpoint Percent Response(line)',
    comp: 'ChartResponseLine',
    title: 'Endpoint Percent Response',
    type: 'endpointInfo',
    width: 3,
  },
  {
    o: 'ServiceEndpoint',
    name: 'Dependency Map',
    comp: 'ChartDependency',
    title: 'Dependency Map',
    type: 'endpointInfo',
    width: 6,
  },
  {
    o: 'ServiceEndpoint',
    name: 'Endpoint Top Slow Traces',
    comp: 'ChartTrace',
    title: 'Endpoint Top Slow Traces',
    type: 'endpointInfo.queryBasicTraces',
    width: 6,
  },
  {
    o: 'Global',
    name: 'Global Top Slow Endpoint',
    comp: 'ChartSlow',
    title: 'Global Top Slow Endpoint',
    type: 'global.getTopNSlowEndpoint',
    width: 6,
  },
];
