export default [
  {
    o: 'Global',
    name: 'Global Brief',
    comp: 'ChartBrief',
    title: 'Global Brief',
    type: 'global',
    width: 3,
  },
  {
    o: 'Service',
    name: 'Service Avg Response',
    comp: 'ChartAvgResponse',
    title: 'Service Avg Response',
    type: 'serviceInfo',
    width: 3,
  },
  {
    o: 'Service',
    name: 'Service Avg Throughput',
    comp: 'ChartAvgThroughput',
    title: 'Service Avg Throughput',
    type: 'serviceInfo',
    width: 3,
  },
  {
    o: 'Service',
    name: 'Service Avg SLA',
    comp: 'ChartAvgSLA',
    title: 'Service Avg SLA',
    type: 'serviceInfo',
    width: 3,
  },
  {
    o: 'Global',
    name: 'Global Percent Response(line)',
    comp: 'ChartResponseLine',
    title: 'Global Percent Response',
    type: 'global',
    width: 3,
  },
  {
    o: 'Service',
    name: 'Service Percent Response(line)',
    comp: 'ChartResponseLine',
    title: 'Service Percent Response',
    type: 'serviceInfo',
    width: 3,
  },
  {
    o: 'Service',
    name: 'Service Top Slow Endpoint',
    comp: 'ChartSlow',
    title: 'Service Top Slow Endpoint',
    type: 'serviceInfo.getSlowEndpoint',
    width: 3,
  },
  {
    o: 'Service',
    name: 'Running ServiceInstance',
    comp: 'ChartTroughput',
    title: 'Running ServiceInstance',
    type: 'serviceInfo.getInstanceThroughput',
    width: 3,
  },
];
