/**
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default [
  {
    chartType: 'ChartNum',
    title: 'Database Avg ResponseTime',
    width: 3,
    height: 250,
    metricName: 'database_access_resp_time',
    queryMetricType: 'readMetricsValue',
    entityType: 'Service',
    independentSelector: false,
    metricType: 'REGULAR_VALUE',
    unit: 'ms',
    aggregation: '',
    aggregationNum: 0,
    normal: false,
  },
  {
    chartType: 'ChartNum',
    title: 'Database Avg Throughput',
    width: 3,
    height: 250,
    metricName: 'database_access_cpm',
    queryMetricType: 'readMetricsValue',
    entityType: 'Service',
    independentSelector: false,
    metricType: 'REGULAR_VALUE',
    unit: 'ms',
    aggregation: '',
    aggregationNum: null,
    normal: false,
  },
  {
    chartType: 'ChartNum',
    title: 'Database Avg SLA',
    width: 3,
    height: 250,
    metricName: 'database_access_sla',
    queryMetricType: 'readMetricsValue',
    entityType: 'Service',
    independentSelector: false,
    metricType: 'REGULAR_VALUE',
    unit: '%',
    aggregation: '/',
    aggregationNum: 100,
    normal: false,
  },
  {
    chartType: 'ChartLine',
    title: 'Database ResponseTime',
    width: 3,
    height: 250,
    metricName: 'database_access_resp_time',
    queryMetricType: 'readMetricsValues',
    entityType: 'Service',
    independentSelector: false,
    metricType: 'REGULAR_VALUE',
    unit: 'ms',
    aggregation: '',
    aggregationNum: null,
    normal: false,
  },
  {
    chartType: 'ChartLine',
    title: 'Database Throughput',
    width: 3,
    height: 250,
    metricName: 'database_access_cpm',
    queryMetricType: 'readMetricsValues',
    entityType: 'Service',
    independentSelector: false,
    metricType: 'REGULAR_VALUE',
    unit: 'ms',
    aggregation: '',
    aggregationNum: null,
    normal: false,
  },
  {
    chartType: 'ChartLine',
    title: 'Database SLA',
    width: 3,
    height: 250,
    metricName: 'database_access_sla',
    queryMetricType: 'readMetricsValues',
    entityType: 'Service',
    independentSelector: false,
    metricType: 'REGULAR_VALUE',
    unit: '%',
    aggregation: '/',
    aggregationNum: 100,
    normal: false,
  },
  {
    chartType: 'ChartLine',
    title: 'Global Response Time Percentile',
    width: 6,
    height: 250,
    metricName: 'all_percentile',
    queryMetricType: 'readLabeledMetricsValues',
    entityType: 'All',
    independentSelector: false,
    metricType: 'LABELED_VALUE',
    metricLabels: 'p50, p75, p90, p95, p99',
    labelsIndex: '0, 1, 2, 3, 4',
    unit: '',
    aggregation: '',
    aggregationNum: null,
    normal: true,
  },
  {
    chartType: 'ChartLine',
    title: 'Database Response Time Percentile',
    width: 3,
    height: 250,
    metricName: 'database_access_percentile',
    queryMetricType: 'readLabeledMetricsValues',
    entityType: 'Service',
    independentSelector: false,
    metricType: 'LABELED_VALUE',
    metricLabels: 'p50, p75, p90, p95, p99',
    labelsIndex: '0, 1, 2, 3, 4',
    aggregation: '',
    aggregationNum: null,
    unit: '',
    normal: false,
  },
  {
    chartType: 'ChartSlow',
    title: 'Database TopN Records',
    width: 6,
    height: 250,
    metricName: 'top_n_database_statement',
    queryMetricType: 'readSampledRecords',
    entityType: 'Service',
    independentSelector: false,
    metricType: 'SAMPLED_RECORD',
    aggregation: '',
    aggregationNum: null,
    unit: '',
    parentService: true,
    normal: false,
  },
];
