/**
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default [
  {
    chartType: 'ChartNum',
    title: 'Service Avg ApdexScore',
    width: 3,
    height: 80,
    metricName: 'service_apdex',
    queryMetricType: 'readMetricsValue',
    entityType: 'Service',
    independentSelector: false,
    metricType: 'REGULAR_VALUE',
    version: '1.0',
    unit: '',
    aggregation: '/',
    aggregationNum: 10000,
    normal: true,
  },
  {
    chartType: 'ChartNum',
    title: 'Service Avg ResponseTime',
    width: 3,
    height: 80,
    metricName: 'service_resp_time',
    queryMetricType: 'readMetricsValue',
    entityType: 'Service',
    independentSelector: false,
    metricType: 'REGULAR_VALUE',
    aggregation: '',
    aggregationNum: null,
    unit: 'ms',
    normal: true,
  },
  {
    chartType: 'ChartNum',
    title: 'Service Avg Throughput',
    width: 3,
    height: 80,
    metricName: 'service_cpm',
    queryMetricType: 'readMetricsValue',
    entityType: 'Service',
    independentSelector: false,
    metricType: 'REGULAR_VALUE',
    aggregation: '',
    aggregationNum: null,
    unit: 'ms',
    normal: true,
  },
  {
    chartType: 'ChartNum',
    title: 'Service Avg SLA',
    width: 3,
    height: 80,
    metricName: 'service_sla',
    queryMetricType: 'readMetricsValue',
    entityType: 'Service',
    independentSelector: false,
    metricType: 'REGULAR_VALUE',
    unit: '%',
    aggregation: '/',
    aggregationNum: 100,
    normal: true,
  },
  {
    chartType: 'ChartLine',
    title: 'Service ApdexScore',
    width: 3,
    height: 170,
    metricName: 'service_apdex',
    queryMetricType: 'readMetricsValues',
    entityType: 'Service',
    independentSelector: false,
    metricType: 'REGULAR_VALUE',
    unit: '',
    aggregation: '/',
    aggregationNum: 10000,
    normal: true,
  },
  {
    chartType: 'ChartLine',
    title: 'Service ResponseTime',
    width: 3,
    height: 170,
    metricName: 'service_resp_time',
    queryMetricType: 'readMetricsValues',
    entityType: 'Service',
    independentSelector: false,
    metricType: 'REGULAR_VALUE',
    aggregation: '',
    aggregationNum: null,
    unit: '',
    normal: true,
  },
  {
    chartType: 'ChartLine',
    title: 'Service Throughput',
    width: 3,
    height: 170,
    metricName: 'service_cpm',
    queryMetricType: 'readMetricsValues',
    entityType: 'Service',
    independentSelector: false,
    metricType: 'REGULAR_VALUE',
    aggregation: '',
    aggregationNum: null,
    unit: '',
    normal: true,
  },
  {
    chartType: 'ChartLine',
    title: 'Service SLA',
    width: 3,
    height: 170,
    metricName: 'service_sla',
    queryMetricType: 'readMetricsValues',
    entityType: 'Service',
    independentSelector: false,
    metricType: 'REGULAR_VALUE',
    unit: '%',
    aggregation: '/',
    aggregationNum: 100,
    normal: true,
  },
  {
    chartType: 'ChartLine',
    title: 'Global Response Time Percentile',
    width: 3,
    height: 250,
    metricName: 'all_percentile',
    queryMetricType: 'readLabeledMetricsValues',
    entityType: 'All',
    independentSelector: false,
    metricType: 'LABELED_VALUE',
    metricLabels: 'p50, p75, p90, p95, p99',
    labelsIndex: '0, 1, 2, 3, 4',
    aggregation: '',
    aggregationNum: null,
    unit: '',
    normal: true,
  },
  {
    chartType: 'ChartLine',
    title: 'Service Response Time Percentile',
    width: 3,
    height: 250,
    metricName: 'service_percentile',
    queryMetricType: 'readLabeledMetricsValues',
    entityType: 'Service',
    independentSelector: false,
    metricType: 'LABELED_VALUE',
    metricLabels: 'p50, p75, p90, p95, p99',
    labelsIndex: '0, 1, 2, 3, 4',
    aggregation: '',
    aggregationNum: null,
    unit: '',
    normal: true,
  },
  {
    chartType: 'ChartSlow',
    title: 'Service Slow Endpoint',
    width: 3,
    height: 250,
    metricName: 'endpoint_avg',
    queryMetricType: 'sortMetrics',
    entityType: 'Endpoint',
    independentSelector: false,
    metricType: 'REGULAR_VALUE',
    aggregation: '',
    aggregationNum: null,
    unit: 'ms',
    parentService: true,
    normal: true,
  },
  {
    chartType: 'ChartTrace',
    title: 'Running ServiceInstance',
    width: 3,
    height: 250,
    metricName: 'service_instance_cpm',
    queryMetricType: 'sortMetrics',
    entityType: 'ServiceInstance',
    independentSelector: false,
    metricType: 'REGULAR_VALUE',
    aggregation: '',
    aggregationNum: null,
    unit: 'cpm',
    parentService: true,
    normal: true,
  },
];
